config/routes.rb
Rails.application.routes.draw do

  resources :pokemons
  root 'pokemons#index'

end

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

  def index
    @pokemons = Pokemon.all
  end

  def new
  end

  def create
    @pokemon = Pokemon.new(pokemon_params) #params from from
    @pokemon.save
    redirect_to pokemon_path(@pokemon) 
    #Redirect to show action, look at rake routes prefix                                       #pokemon_path, last line could also be redirect_to @pokemon

  end

  def show
    @pokemon = Pokemon.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

    def pokemon_params
      params.require(:pokemon).permit(:name,:description)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PokemonApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pokemons/create.html.erb
<h1>Pokemons#create</h1>
<p>Find me in app/views/pokemons/create.html.erb</p>

app/views/pokemons/destroy.html.erb
<h1>Pokemons#destroy</h1>
<p>Find me in app/views/pokemons/destroy.html.erb</p>

app/views/pokemons/edit.html.erb
<h1>Pokemons#edit</h1>
<p>Find me in app/views/pokemons/edit.html.erb</p>

app/views/pokemons/index.html.erb
<h1> Your Pokedex </h1>

<%= link_to 'Add new pokemon', new_pokemon_path %>

<% @pokemons.each do |pokemon| %>
  <tr>
    <h3>Name:</h3>
    <td><%= pokemon.name %></td> 
    <h3>Description:</h3>
    <td><%= pokemon.description %></td>
    </br>
    </br>
  </tr>
<% end %>

app/views/pokemons/new.html.erb
<h1> Our form to create a pokemon </h1>



<%= simple_form_for Pokemon.new do |f| %> <!--auto redirect to show-->
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>





<%
=begin %> 
<!--begin comment-->

<%= form_for Pokemon.new, url: pokemons_path do |f| %> <!--url can be this or {action:"create"}, url sends to pokemon#create-->
  Title: <%= f.text_field :name %>
  Description: <%= f.text_area :description %>
  <%= f.submit "Create" %>
<% end %>

<%
=end %> 
<!--end comment-->

app/views/pokemons/show.html.erb
<h1>Pokemon Details: </h1>
<h3>Name: </h3>
<%= @pokemon.name %>
<h3>Description: </h3>
<%= @pokemon.description %>

</br></br>
<%= link_to 'My Pokedex', pokemons_path %>

app/views/pokemons/update.html.erb
<h1>Pokemons#update</h1>
<p>Find me in app/views/pokemons/update.html.erb</p>